<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountyStatesTableSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ["county" => "Adams", "display" => "Adams, PA", "fips" => 42001, "state" => "PA", "slug" => "adams-pa"],
            ["county" => "Adams", "display" => "Adams, PE", "fips" => 21001, "state" => "PE", "slug" => "adams-pe"],
            ["county" => "Allegany", "display" => "Allegany, MD", "fips" => 24001, "state" => "MD", "slug" => "allegany-md"],
            ["county" => "Accomack", "display" => "Accomack, VA", "fips" => 51001, "state" => "VA", "slug" => "accomack-va"],
            ["county" => "Albemarle", "display" => "Albemarle, VA", "fips" => 51003, "state" => "VA", "slug" => "albemarle-va"],
            ["county" => "Alexandria City", "display" => "Alexandria City, VA", "fips" => 51510, "state" => "VA", "slug" => "alexandria-city-va"],
            ["county" => "Alleghany", "display" => "Alleghany, VA", "fips" => 51005, "state" => "VA", "slug" => "alleghany-va"],
            ["county" => "Amelia", "display" => "Amelia, VA", "fips" => 51007, "state" => "VA", "slug" => "amelia-va"],
            ["county" => "Amherst", "display" => "Amherst, VA", "fips" => 51009, "state" => "VA", "slug" => "amherst-va"],
            ["county" => "Allegheny", "display" => "Allegheny, PA", "fips" => 42003, "state" => "PA", "slug" => "allegheny-pa"],
            ["county" => "Arlington", "display" => "Arlington, VA", "fips" => 51013, "state" => "VA", "slug" => "arlington-va"],
            ["county" => "Anne Arundel", "display" => "Anne Arundel, MD", "fips" => 24003, "state" => "MD", "slug" => "anne-arundel-md"],
            ["county" => "Appomattox", "display" => "Appomattox, VA", "fips" => 51011, "state" => "VA", "slug" => "appomattox-va"],
            ["county" => "Atlantic", "display" => "Atlantic, NJ", "fips" => 34001, "state" => "NJ", "slug" => "atlantic-nj"],
            ["county" => "Armstrong", "display" => "Armstrong, PA", "fips" => 42005, "state" => "PA", "slug" => "armstrong-pa"],
            ["county" => "Augusta", "display" => "Augusta, VA", "fips" => 51015, "state" => "VA", "slug" => "augusta-va"],
            ["county" => "Baltimore", "display" => "Baltimore, MD", "fips" => 24005, "state" => "MD", "slug" => "baltimore-md"],
            ["county" => "Baltimore City", "display" => "Baltimore City, MD", "fips" => 24510, "state" => "MD", "slug" => "baltimore-city-md"],
            ["county" => "Barbour", "display" => "Barbour, WV", "fips" => 54001, "state" => "WV", "slug" => "barbour-wv"],
            ["county" => "Bath", "display" => "Bath, VA", "fips" => 51017, "state" => "VA", "slug" => "bath-va"],
            ["county" => "Bedford", "display" => "Bedford, VA", "fips" => 51019, "state" => "VA", "slug" => "bedford-va"],
            ["county" => "Beaver", "display" => "Beaver, PA", "fips" => 42007, "state" => "PA", "slug" => "beaver-pa"],
            ["county" => "Bedford", "display" => "Bedford, PA", "fips" => 42009, "state" => "PA", "slug" => "bedford-pa"],
            ["county" => "Blair", "display" => "Blair, PA", "fips" => 42013, "state" => "PA", "slug" => "blair-pa"],
            ["county" => "Berkeley", "display" => "Berkeley, WV", "fips" => 54003, "state" => "WV", "slug" => "berkeley-wv"],
            ["county" => "Berks", "display" => "Berks, PA", "fips" => 42011, "state" => "PA", "slug" => "berks-pa"],
            ["county" => "Bland", "display" => "Bland, VA", "fips" => 51021, "state" => "VA", "slug" => "bland-va"],
            ["county" => "Bradford", "display" => "Bradford, PA", "fips" => 42015, "state" => "PA", "slug" => "bradford-pa"],
            ["county" => "Botetourt", "display" => "Botetourt, VA", "fips" => 51023, "state" => "VA", "slug" => "botetourt-va"],
            ["county" => "Bergen", "display" => "Bergen, NJ", "fips" => 34003, "state" => "NJ", "slug" => "bergen-nj"],
            ["county" => "Braxton", "display" => "Braxton, WV", "fips" => 54007, "state" => "WV", "slug" => "braxton-wv"],
            ["county" => "Cabell", "display" => "Cabell, WV", "fips" => 54011, "state" => "WV", "slug" => "cabell-wv"],
            ["county" => "Calvert", "display" => "Calvert, MD", "fips" => 24009, "state" => "MD", "slug" => "calvert-md"],
            ["county" => "Brooke", "display" => "Brooke, WV", "fips" => 54009, "state" => "WV", "slug" => "brooke-wv"],
            ["county" => "Brunswick", "display" => "Brunswick, VA", "fips" => 51025, "state" => "VA", "slug" => "brunswick-va"],
            ["county" => "Butler", "display" => "Butler, PA", "fips" => 42019, "state" => "PA", "slug" => "butler-pa"],
            ["county" => "Bucks", "display" => "Bucks, 0", "fips" => 0, "state" => "0", "slug" => "bucks-0"],
            ["county" => "Burlington", "display" => "Burlington, NJ", "fips" => 34005, "state" => "NJ", "slug" => "burlington-nj"],
            ["county" => "Bucks", "display" => "Bucks, PA", "fips" => 42017, "state" => "PA", "slug" => "bucks-pa"],
            ["county" => "Buckingham", "display" => "Buckingham, VA", "fips" => 51029, "state" => "VA", "slug" => "buckingham-va"],
            ["county" => "Cambria", "display" => "Cambria, PA", "fips" => 42021, "state" => "PA", "slug" => "cambria-pa"],
            ["county" => "Camden", "display" => "Camden, NJ", "fips" => 34007, "state" => "NJ", "slug" => "camden-nj"],
            ["county" => "Camden", "display" => "Camden, 0", "fips" => 0, "state" => "0", "slug" => "camden-0"],
            ["county" => "Carroll", "display" => "Carroll, MD", "fips" => 24013, "state" => "MD", "slug" => "carroll-md"],
            ["county" => "Campbell", "display" => "Campbell, VA", "fips" => 51031, "state" => "VA", "slug" => "campbell-va"],
            ["county" => "Cameron", "display" => "Cameron, PA", "fips" => 42023, "state" => "PA", "slug" => "cameron-pa"],
            ["county" => "Cape May", "display" => "Cape May, NJ", "fips" => 34009, "state" => "NJ", "slug" => "cape-may-nj"],
            ["county" => "Carbon", "display" => "Carbon, PA", "fips" => 42025, "state" => "PA", "slug" => "carbon-pa"],
            ["county" => "Caroline", "display" => "Caroline, VA", "fips" => 51033, "state" => "VA", "slug" => "caroline-va"],
            ["county" => "Caroline", "display" => "Caroline, MD", "fips" => 24011, "state" => "MD", "slug" => "caroline-md"],
            ["county" => "Cecil", "display" => "Cecil, MD", "fips" => 24015, "state" => "MD", "slug" => "cecil-md"],
            ["county" => "Centre", "display" => "Centre, IA", "fips" => 1019, "state" => "IA", "slug" => "centre-ia"],
            ["county" => "Centre", "display" => "Centre, PA", "fips" => 42027, "state" => "PA", "slug" => "centre-pa"],
            ["county" => "Centre", "display" => "Centre, ID", "fips" => 1019, "state" => "ID", "slug" => "centre-id"],
            ["county" => "Carroll", "display" => "Carroll, PA", "fips" => 42029, "state" => "PA", "slug" => "carroll-pa"],
            ["county" => "Charles", "display" => "Charles, MD", "fips" => 24017, "state" => "MD", "slug" => "charles-md"],
            ["county" => "Chesterfield", "display" => "Chesterfield, VA", "fips" => 51041, "state" => "VA", "slug" => "chesterfield-va"],
            ["county" => "Chester", "display" => "Chester, PA", "fips" => 42029, "state" => "PA", "slug" => "chester-pa"],
            ["county" => "Chesapeake City", "display" => "Chesapeake City, VA", "fips" => 51550, "state" => "VA", "slug" => "chesapeake-city-va"],
            ["county" => "Charles City", "display" => "Charles City, VA", "fips" => 51036, "state" => "VA", "slug" => "charles-city-va"],
            ["county" => "Charlotte", "display" => "Charlotte, VA", "fips" => 51037, "state" => "VA", "slug" => "charlotte-va"],
            ["county" => "Charlottesville City", "display" => "Charlottesville City, VA", "fips" => 51540, "state" => "VA", "slug" => "charlottesville-city-va"],
            ["county" => "Clarke", "display" => "Clarke, VA", "fips" => 51043, "state" => "VA", "slug" => "clarke-va"],
            ["county" => "Clearfield", "display" => "Clearfield, NY", "fips" => 36123, "state" => "NY", "slug" => "clearfield-ny"],
            ["county" => "Colonial Heights City", "display" => "Colonial Heights City, VA", "fips" => 51570, "state" => "VA", "slug" => "colonial-heights-city-va"],
            ["county" => "Clay", "display" => "Clay, WV", "fips" => 54015, "state" => "WV", "slug" => "clay-wv"],
            ["county" => "Clearfield", "display" => "Clearfield, PA", "fips" => 42033, "state" => "PA", "slug" => "clearfield-pa"],
            ["county" => "Columbia", "display" => "Columbia, PA", "fips" => 42037, "state" => "PA", "slug" => "columbia-pa"],
            ["county" => "Clarion", "display" => "Clarion, PA", "fips" => 42031, "state" => "PA", "slug" => "clarion-pa"],
            ["county" => "Clinton", "display" => "Clinton, PA", "fips" => 42035, "state" => "PA", "slug" => "clinton-pa"],
            ["county" => "Dauphin", "display" => "Dauphin, NC", "fips" => 42043, "state" => "NC", "slug" => "dauphin-nc"],
            ["county" => "Cumberland", "display" => "Cumberland, VA", "fips" => 51049, "state" => "VA", "slug" => "cumberland-va"],
            ["county" => "Cumberland", "display" => "Cumberland, NJ", "fips" => 34011, "state" => "NJ", "slug" => "cumberland-nj"],
            ["county" => "Dauphin", "display" => "Dauphin, MI", "fips" => 42043, "state" => "MI", "slug" => "dauphin-mi"],
            ["county" => "Crawford", "display" => "Crawford, PA", "fips" => 42039, "state" => "PA", "slug" => "crawford-pa"],
            ["county" => "Culpeper", "display" => "Culpeper, VA", "fips" => 51047, "state" => "VA", "slug" => "culpeper-va"],
            ["county" => "Cumberland", "display" => "Cumberland, PA", "fips" => 42041, "state" => "PA", "slug" => "cumberland-pa"],
            ["county" => "Dauphin", "display" => "Dauphin, PA", "fips" => 42043, "state" => "PA", "slug" => "dauphin-pa"],
            ["county" => "Dauphin", "display" => "Dauphin, IN", "fips" => 42043, "state" => "IN", "slug" => "dauphin-in"],
            ["county" => "Delaware", "display" => "Delaware, PA", "fips" => 42045, "state" => "PA", "slug" => "delaware-pa"],
            ["county" => "Essex", "display" => "Essex, VA", "fips" => 51057, "state" => "VA", "slug" => "essex-va"],
            ["county" => "Fairfax City", "display" => "Fairfax City, VA", "fips" => 51600, "state" => "VA", "slug" => "fairfax-city-va"],
            ["county" => "Dinwiddie", "display" => "Dinwiddie, VA", "fips" => 51053, "state" => "VA", "slug" => "dinwiddie-va"],
            ["county" => "Elk", "display" => "Elk, PA", "fips" => 42047, "state" => "PA", "slug" => "elk-pa"],
            ["county" => "Doddridge", "display" => "Doddridge, WV", "fips" => 54017, "state" => "WV", "slug" => "doddridge-wv"],
            ["county" => "Essex", "display" => "Essex, NJ", "fips" => 34013, "state" => "NJ", "slug" => "essex-nj"],
            ["county" => "Falls Church City", "display" => "Falls Church City, VA", "fips" => 51610, "state" => "VA", "slug" => "falls-church-city-va"],
            ["county" => "Dorchester", "display" => "Dorchester, MD", "fips" => 24019, "state" => "MD", "slug" => "dorchester-md"],
            ["county" => "Fairfax", "display" => "Fairfax, VA", "fips" => 51059, "state" => "VA", "slug" => "fairfax-va"],
            ["county" => "Erie", "display" => "Erie, PA", "fips" => 42049, "state" => "PA", "slug" => "erie-pa"],
            ["county" => "Fayette", "display" => "Fayette, PA", "fips" => 42051, "state" => "PA", "slug" => "fayette-pa"],
            ["county" => "Floyd", "display" => "Floyd, VA", "fips" => 51063, "state" => "VA", "slug" => "floyd-va"],
            ["county" => "Fauquier", "display" => "Fauquier, VA", "fips" => 51061, "state" => "VA", "slug" => "fauquier-va"],
            ["county" => "Fredericksburg City", "display" => "Fredericksburg City, VA", "fips" => 51630, "state" => "VA", "slug" => "fredericksburg-city-va"],
            ["county" => "Franklin", "display" => "Franklin, VA", "fips" => 51067, "state" => "VA", "slug" => "franklin-va"],
            ["county" => "Fluvanna", "display" => "Fluvanna, VA", "fips" => 51065, "state" => "VA", "slug" => "fluvanna-va"],
            ["county" => "Frederick", "display" => "Frederick, MD", "fips" => 24021, "state" => "MD", "slug" => "frederick-md"],
            ["county" => "Frederick", "display" => "Frederick, VA", "fips" => 51069, "state" => "VA", "slug" => "frederick-va"],
            ["county" => "Franklin", "display" => "Franklin, WA", "fips" => 53021, "state" => "WA", "slug" => "franklin-wa"],
            ["county" => "Franklin", "display" => "Franklin, PA", "fips" => 42055, "state" => "PA", "slug" => "franklin-pa"],
            ["county" => "Fulton", "display" => "Fulton, PA", "fips" => 42057, "state" => "PA", "slug" => "fulton-pa"],
            ["county" => "Garrett", "display" => "Garrett, MD", "fips" => 24023, "state" => "MD", "slug" => "garrett-md"],
            ["county" => "Grant", "display" => "Grant, WV", "fips" => 54023, "state" => "WV", "slug" => "grant-wv"],
            ["county" => "Goochland", "display" => "Goochland, VA", "fips" => 51075, "state" => "VA", "slug" => "goochland-va"],
            ["county" => "Gloucester", "display" => "Gloucester, NJ", "fips" => 34015, "state" => "NJ", "slug" => "gloucester-nj"],
            ["county" => "Gloucester", "display" => "Gloucester, VA", "fips" => 51073, "state" => "VA", "slug" => "gloucester-va"],
            ["county" => "Gilmer", "display" => "Gilmer, WV", "fips" => 54021, "state" => "WV", "slug" => "gilmer-wv"],
            ["county" => "Greenbrier", "display" => "Greenbrier, WV", "fips" => 54025, "state" => "WV", "slug" => "greenbrier-wv"],
            ["county" => "Greene", "display" => "Greene, PA", "fips" => 42059, "state" => "PA", "slug" => "greene-pa"],
            ["county" => "Grayson", "display" => "Grayson, VA", "fips" => 51077, "state" => "VA", "slug" => "grayson-va"],
            ["county" => "Halifax", "display" => "Halifax, VA", "fips" => 51083, "state" => "VA", "slug" => "halifax-va"],
            ["county" => "Greene", "display" => "Greene, VA", "fips" => 51079, "state" => "VA", "slug" => "greene-va"],
            ["county" => "Greensville", "display" => "Greensville, VA", "fips" => 51081, "state" => "VA", "slug" => "greensville-va"],
            ["county" => "Hancock", "display" => "Hancock, WV", "fips" => 54029, "state" => "WV", "slug" => "hancock-wv"],
            ["county" => "Hampshire", "display" => "Hampshire, WV", "fips" => 54027, "state" => "WV", "slug" => "hampshire-wv"],
            ["county" => "Hampton City", "display" => "Hampton City, VA", "fips" => 51650, "state" => "VA", "slug" => "hampton-city-va"],
            ["county" => "Harford", "display" => "Harford, MD", "fips" => 24025, "state" => "MD", "slug" => "harford-md"],
            ["county" => "Harrison", "display" => "Harrison, WV", "fips" => 54033, "state" => "WV", "slug" => "harrison-wv"],
            ["county" => "Hanover", "display" => "Hanover, VA", "fips" => 51085, "state" => "VA", "slug" => "hanover-va"],
            ["county" => "Hardy", "display" => "Hardy, WV", "fips" => 54031, "state" => "WV", "slug" => "hardy-wv"],
            ["county" => "Highland", "display" => "Highland, VA", "fips" => 51091, "state" => "VA", "slug" => "highland-va"],
            ["county" => "Hudson", "display" => "Hudson, NJ", "fips" => 34017, "state" => "NJ", "slug" => "hudson-nj"],
            ["county" => "Howard", "display" => "Howard, MD", "fips" => 24027, "state" => "MD", "slug" => "howard-md"],
            ["county" => "Hunterdon", "display" => "Hunterdon, NJ", "fips" => 34019, "state" => "NJ", "slug" => "hunterdon-nj"],
            ["county" => "Henrico", "display" => "Henrico, VA", "fips" => 51087, "state" => "VA", "slug" => "henrico-va"],
            ["county" => "Hopewell City", "display" => "Hopewell City, VA", "fips" => 51670, "state" => "VA", "slug" => "hopewell-city-va"],
            ["county" => "Henry", "display" => "Henry, VA", "fips" => 51089, "state" => "VA", "slug" => "henry-va"],
            ["county" => "Harrisonburg City", "display" => "Harrisonburg City, VA", "fips" => 51660, "state" => "VA", "slug" => "harrisonburg-city-va"],
            ["county" => "Huntingdon", "display" => "Huntingdon, NY", "fips" => 42061, "state" => "NY", "slug" => "huntingdon-ny"],
            ["county" => "Huntingdon", "display" => "Huntingdon, PA", "fips" => 42061, "state" => "PA", "slug" => "huntingdon-pa"],
            ["county" => "Indiana", "display" => "Indiana, PA", "fips" => 42063, "state" => "PA", "slug" => "indiana-pa"],
            ["county" => "King And Queen", "display" => "King And Queen, VA", "fips" => 51097, "state" => "VA", "slug" => "king-and-queen-va"],
            ["county" => "Kent", "display" => "Kent, DE", "fips" => 10001, "state" => "DE", "slug" => "kent-de"],
            ["county" => "Isle Of Wight", "display" => "Isle Of Wight, VA", "fips" => 51093, "state" => "VA", "slug" => "isle-of-wight-va"],
            ["county" => "Juniata", "display" => "Juniata, MS", "fips" => 28085, "state" => "MS", "slug" => "juniata-ms"],
            ["county" => "Jefferson", "display" => "Jefferson, WV", "fips" => 54037, "state" => "WV", "slug" => "jefferson-wv"],
            ["county" => "Jefferson", "display" => "Jefferson, PA", "fips" => 42065, "state" => "PA", "slug" => "jefferson-pa"],
            ["county" => "Kent", "display" => "Kent, MD", "fips" => 24029, "state" => "MD", "slug" => "kent-md"],
            ["county" => "Juniata", "display" => "Juniata, PA", "fips" => 42067, "state" => "PA", "slug" => "juniata-pa"],
            ["county" => "James City", "display" => "James City, VA", "fips" => 51095, "state" => "VA", "slug" => "james-city-va"],
            ["county" => "Lebanon", "display" => "Lebanon, PA", "fips" => 42075, "state" => "PA", "slug" => "lebanon-pa"],
            ["county" => "King George", "display" => "King George, VA", "fips" => 51099, "state" => "VA", "slug" => "king-george-va"],
            ["county" => "Lehigh", "display" => "Lehigh, PA", "fips" => 42077, "state" => "PA", "slug" => "lehigh-pa"],
            ["county" => "Lancaster", "display" => "Lancaster, VA", "fips" => 51103, "state" => "VA", "slug" => "lancaster-va"],
            ["county" => "King William", "display" => "King William, VA", "fips" => 51101, "state" => "VA", "slug" => "king-william-va"],
            ["county" => "Lexington City", "display" => "Lexington City, VA", "fips" => 51678, "state" => "VA", "slug" => "lexington-city-va"],
            ["county" => "Lawrence", "display" => "Lawrence, PA", "fips" => 42073, "state" => "PA", "slug" => "lawrence-pa"],
            ["county" => "Lancaster", "display" => "Lancaster, PA", "fips" => 42071, "state" => "PA", "slug" => "lancaster-pa"],
            ["county" => "Loudoun", "display" => "Loudoun, VA", "fips" => 51107, "state" => "VA", "slug" => "loudoun-va"],
            ["county" => "Lackawanna", "display" => "Lackawanna, PA", "fips" => 42069, "state" => "PA", "slug" => "lackawanna-pa"],
            ["county" => "Luzerne", "display" => "Luzerne, PA", "fips" => 42079, "state" => "PA", "slug" => "luzerne-pa"],
            ["county" => "Louisa", "display" => "Louisa, VA", "fips" => 51109, "state" => "VA", "slug" => "louisa-va"],
            ["county" => "Lycoming", "display" => "Lycoming, PA", "fips" => 42081, "state" => "PA", "slug" => "lycoming-pa"],
            ["county" => "Lunenburg", "display" => "Lunenburg, VA", "fips" => 51111, "state" => "VA", "slug" => "lunenburg-va"],
            ["county" => "Lynchburg City", "display" => "Lynchburg City, VA", "fips" => 51680, "state" => "VA", "slug" => "lynchburg-city-va"],
            ["county" => "Marion", "display" => "Marion, WV", "fips" => 54049, "state" => "WV", "slug" => "marion-wv"],
            ["county" => "Manassas City", "display" => "Manassas City, VA", "fips" => 51683, "state" => "VA", "slug" => "manassas-city-va"],
            ["county" => "Manassas Park City", "display" => "Manassas Park City, VA", "fips" => 51685, "state" => "VA", "slug" => "manassas-park-city-va"],
            ["county" => "Mathews", "display" => "Mathews, VA", "fips" => 51115, "state" => "VA", "slug" => "mathews-va"],
            ["county" => "Madison", "display" => "Madison, VA", "fips" => 51113, "state" => "VA", "slug" => "madison-va"],
            ["county" => "Middlesex", "display" => "Middlesex, NJ", "fips" => 34023, "state" => "NJ", "slug" => "middlesex-nj"],
            ["county" => "Mercer", "display" => "Mercer, NJ", "fips" => 34021, "state" => "NJ", "slug" => "mercer-nj"],
            ["county" => "Mecklenburg", "display" => "Mecklenburg, VA", "fips" => 51117, "state" => "VA", "slug" => "mecklenburg-va"],
            ["county" => "Mercer", "display" => "Mercer, PA", "fips" => 42085, "state" => "PA", "slug" => "mercer-pa"],
            ["county" => "Mckean", "display" => "Mckean, PA", "fips" => 42083, "state" => "PA", "slug" => "mckean-pa"],
            ["county" => "Mifflin", "display" => "Mifflin, PA", "fips" => 42087, "state" => "PA", "slug" => "mifflin-pa"],
            ["county" => "Mineral", "display" => "Mineral, WV", "fips" => 54057, "state" => "WV", "slug" => "mineral-wv"],
            ["county" => "Monmouth", "display" => "Monmouth, NJ", "fips" => 34025, "state" => "NJ", "slug" => "monmouth-nj"],
            ["county" => "Mingo", "display" => "Mingo, WV", "fips" => 54059, "state" => "WV", "slug" => "mingo-wv"],
            ["county" => "Middlesex", "display" => "Middlesex, VA", "fips" => 51119, "state" => "VA", "slug" => "middlesex-va"],
            ["county" => "Monongalia", "display" => "Monongalia, WV", "fips" => 54061, "state" => "WV", "slug" => "monongalia-wv"],
            ["county" => "Morris", "display" => "Morris, NJ", "fips" => 34027, "state" => "NJ", "slug" => "morris-nj"],
            ["county" => "Nelson", "display" => "Nelson, VA", "fips" => 51125, "state" => "VA", "slug" => "nelson-va"],
            ["county" => "Monroe", "display" => "Monroe, PA", "fips" => 42089, "state" => "PA", "slug" => "monroe-pa"],
            ["county" => "Montgomery", "display" => "Montgomery, PA", "fips" => 42091, "state" => "PA", "slug" => "montgomery-pa"],
            ["county" => "Montgomery", "display" => "Montgomery, MD", "fips" => 24031, "state" => "MD", "slug" => "montgomery-md"],
            ["county" => "Montour", "display" => "Montour, PA", "fips" => 42093, "state" => "PA", "slug" => "montour-pa"],
            ["county" => "Montgomery", "display" => "Montgomery, VA", "fips" => 51121, "state" => "VA", "slug" => "montgomery-va"],
            ["county" => "New Castle", "display" => "New Castle, DE", "fips" => 10003, "state" => "DE", "slug" => "new-castle-de"],
            ["county" => "Morgan", "display" => "Morgan, WV", "fips" => 54065, "state" => "WV", "slug" => "morgan-wv"],
            ["county" => "Nicholas", "display" => "Nicholas, WV", "fips" => 54067, "state" => "WV", "slug" => "nicholas-wv"],
            ["county" => "Norfolk City", "display" => "Norfolk City, VA", "fips" => 51710, "state" => "VA", "slug" => "norfolk-city-va"],
            ["county" => "Nottoway", "display" => "Nottoway, VA", "fips" => 51135, "state" => "VA", "slug" => "nottoway-va"],
            ["county" => "Northampton", "display" => "Northampton, PA", "fips" => 42095, "state" => "PA", "slug" => "northampton-pa"],
            ["county" => "New Kent", "display" => "New Kent, VA", "fips" => 51127, "state" => "VA", "slug" => "new-kent-va"],
            ["county" => "Northampton", "display" => "Northampton, VA", "fips" => 51131, "state" => "VA", "slug" => "northampton-va"],
            ["county" => "Northumberland", "display" => "Northumberland, PA", "fips" => 42097, "state" => "PA", "slug" => "northumberland-pa"],
            ["county" => "Newport News City", "display" => "Newport News City, VA", "fips" => 51700, "state" => "VA", "slug" => "newport-news-city-va"],
            ["county" => "Northumberland", "display" => "Northumberland, VA", "fips" => 51133, "state" => "VA", "slug" => "northumberland-va"],
            ["county" => "Ocean", "display" => "Ocean, NJ", "fips" => 34029, "state" => "NJ", "slug" => "ocean-nj"],
            ["county" => "Orange", "display" => "Orange, VA", "fips" => 51137, "state" => "VA", "slug" => "orange-va"],
            ["county" => "Passaic", "display" => "Passaic, NJ", "fips" => 34031, "state" => "NJ", "slug" => "passaic-nj"],
            ["county" => "Ohio", "display" => "Ohio, WV", "fips" => 54069, "state" => "WV", "slug" => "ohio-wv"],
            ["county" => "Perry", "display" => "Perry, PA", "fips" => 42099, "state" => "PA", "slug" => "perry-pa"],
            ["county" => "Orange", "display" => "Orange, FL", "fips" => 12095, "state" => "FL", "slug" => "orange-fl"],
            ["county" => "Petersburg City", "display" => "Petersburg City, VA", "fips" => 51730, "state" => "VA", "slug" => "petersburg-city-va"],
            ["county" => "Page", "display" => "Page, VA", "fips" => 51139, "state" => "VA", "slug" => "page-va"],
            ["county" => "Pendleton", "display" => "Pendleton, WV", "fips" => 54071, "state" => "WV", "slug" => "pendleton-wv"],
            ["county" => "Philadelphia", "display" => "Philadelphia, PA", "fips" => 42101, "state" => "PA", "slug" => "philadelphia-pa"],
            ["county" => "Pike", "display" => "Pike, PA", "fips" => 42103, "state" => "PA", "slug" => "pike-pa"],
            ["county" => "Preston", "display" => "Preston, WV", "fips" => 54077, "state" => "WV", "slug" => "preston-wv"],
            ["county" => "Portsmouth City", "display" => "Portsmouth City, VA", "fips" => 51740, "state" => "VA", "slug" => "portsmouth-city-va"],
            ["county" => "Powhatan", "display" => "Powhatan, VA", "fips" => 51145, "state" => "VA", "slug" => "powhatan-va"],
            ["county" => "Pittsylvania", "display" => "Pittsylvania, VA", "fips" => 51143, "state" => "VA", "slug" => "pittsylvania-va"],
            ["county" => "Prince Georges", "display" => "Prince Georges, MD", "fips" => 24033, "state" => "MD", "slug" => "prince-georges-md"],
            ["county" => "Pocahontas", "display" => "Pocahontas, WV", "fips" => 54075, "state" => "WV", "slug" => "pocahontas-wv"],
            ["county" => "Poquoson City", "display" => "Poquoson City, VA", "fips" => 51735, "state" => "VA", "slug" => "poquoson-city-va"],
            ["county" => "Prince George", "display" => "Prince George, VA", "fips" => 51149, "state" => "VA", "slug" => "prince-george-va"],
            ["county" => "Potter", "display" => "Potter, PA", "fips" => 42105, "state" => "PA", "slug" => "potter-pa"],
            ["county" => "Prince Edward", "display" => "Prince Edward, VA", "fips" => 51147, "state" => "VA", "slug" => "prince-edward-va"],
            ["county" => "Rappahannock", "display" => "Rappahannock, VA", "fips" => 51157, "state" => "VA", "slug" => "rappahannock-va"],
            ["county" => "Prince William", "display" => "Prince William, VA", "fips" => 51153, "state" => "VA", "slug" => "prince-william-va"],
            ["county" => "Ritchie", "display" => "Ritchie, WV", "fips" => 54085, "state" => "WV", "slug" => "ritchie-wv"],
            ["county" => "Pulaski", "display" => "Pulaski, VA", "fips" => 51155, "state" => "VA", "slug" => "pulaski-va"],
            ["county" => "Richmond", "display" => "Richmond, VA", "fips" => 51159, "state" => "VA", "slug" => "richmond-va"],
            ["county" => "Randolph", "display" => "Randolph, WV", "fips" => 54083, "state" => "WV", "slug" => "randolph-wv"],
            ["county" => "Richmond City", "display" => "Richmond City, VA", "fips" => 51760, "state" => "VA", "slug" => "richmond-city-va"],
            ["county" => "Roanoke", "display" => "Roanoke, VA", "fips" => 51161, "state" => "VA", "slug" => "roanoke-va"],
            ["county" => "Queen Annes", "display" => "Queen Annes, MD", "fips" => 24035, "state" => "MD", "slug" => "queen-annes-md"],
            ["county" => "Putnam", "display" => "Putnam, WV", "fips" => 54079, "state" => "WV", "slug" => "putnam-wv"],
            ["county" => "Saint Marys", "display" => "Saint Marys, MD", "fips" => 24037, "state" => "MD", "slug" => "saint-marys-md"],
            ["county" => "Rockbridge", "display" => "Rockbridge, VA", "fips" => 51163, "state" => "VA", "slug" => "rockbridge-va"],
            ["county" => "Russell", "display" => "Russell, VA", "fips" => 51167, "state" => "VA", "slug" => "russell-va"],
            ["county" => "Roanoke City", "display" => "Roanoke City, VA", "fips" => 51770, "state" => "VA", "slug" => "roanoke-city-va"],
            ["county" => "Rockingham", "display" => "Rockingham, VA", "fips" => 51165, "state" => "VA", "slug" => "rockingham-va"],
            ["county" => "Shenandoah", "display" => "Shenandoah, VA", "fips" => 51171, "state" => "VA", "slug" => "shenandoah-va"],
            ["county" => "Salem", "display" => "Salem, NJ", "fips" => 34033, "state" => "NJ", "slug" => "salem-nj"],
            ["county" => "Snyder", "display" => "Snyder, NY", "fips" => 36029, "state" => "NY", "slug" => "snyder-ny"],
            ["county" => "Schuylkill", "display" => "Schuylkill, PA", "fips" => 42107, "state" => "PA", "slug" => "schuylkill-pa"],
            ["county" => "Snyder", "display" => "Snyder, PA", "fips" => 42109, "state" => "PA", "slug" => "snyder-pa"],
            ["county" => "Staunton City", "display" => "Staunton City, VA", "fips" => 51790, "state" => "VA", "slug" => "staunton-city-va"],
            ["county" => "Somerset", "display" => "Somerset, NJ", "fips" => 34035, "state" => "NJ", "slug" => "somerset-nj"],
            ["county" => "Somerset", "display" => "Somerset, MD", "fips" => 24039, "state" => "MD", "slug" => "somerset-md"],
            ["county" => "Suffolk City", "display" => "Suffolk City, VA", "fips" => 51800, "state" => "VA", "slug" => "suffolk-city-va"],
            ["county" => "Somerset", "display" => "Somerset, PA", "fips" => 42111, "state" => "PA", "slug" => "somerset-pa"],
            ["county" => "Snyder", "display" => "Snyder, TX", "fips" => 48415, "state" => "TX", "slug" => "snyder-tx"],
            ["county" => "Sullivan", "display" => "Sullivan, PA", "fips" => 42113, "state" => "PA", "slug" => "sullivan-pa"],
            ["county" => "Spotsylvania", "display" => "Spotsylvania, VA", "fips" => 51177, "state" => "VA", "slug" => "spotsylvania-va"],
            ["county" => "Southampton", "display" => "Southampton, VA", "fips" => 51175, "state" => "VA", "slug" => "southampton-va"],
            ["county" => "Stafford", "display" => "Stafford, VA", "fips" => 51179, "state" => "VA", "slug" => "stafford-va"],
            ["county" => "Surry", "display" => "Surry, VA", "fips" => 51181, "state" => "VA", "slug" => "surry-va"],
            ["county" => "Sussex", "display" => "Sussex, DE", "fips" => 10005, "state" => "DE", "slug" => "sussex-de"],
            ["county" => "Tioga", "display" => "Tioga, PA", "fips" => 42117, "state" => "PA", "slug" => "tioga-pa"],
            ["county" => "Tucker", "display" => "Tucker, WV", "fips" => 54093, "state" => "WV", "slug" => "tucker-wv"],
            ["county" => "Susquehanna", "display" => "Susquehanna, PA", "fips" => 42115, "state" => "PA", "slug" => "susquehanna-pa"],
            ["county" => "Tazewell", "display" => "Tazewell, VA", "fips" => 51185, "state" => "VA", "slug" => "tazewell-va"],
            ["county" => "Sussex", "display" => "Sussex, VA", "fips" => 51183, "state" => "VA", "slug" => "sussex-va"],
            ["county" => "Union", "display" => "Union, NJ", "fips" => 34039, "state" => "NJ", "slug" => "union-nj"],
            ["county" => "Talbot", "display" => "Talbot, MD", "fips" => 24041, "state" => "MD", "slug" => "talbot-md"],
            ["county" => "Sussex", "display" => "Sussex, NJ", "fips" => 34037, "state" => "NJ", "slug" => "sussex-nj"],
            ["county" => "Union", "display" => "Union, PA", "fips" => 42119, "state" => "PA", "slug" => "union-pa"],
            ["county" => "Venango", "display" => "Venango, PA", "fips" => 42121, "state" => "PA", "slug" => "venango-pa"],
            ["county" => "Washington", "display" => "Washington, MD", "fips" => 24043, "state" => "MD", "slug" => "washington-md"],
            ["county" => "Virginia Beach City", "display" => "Virginia Beach City, VA", "fips" => 51810, "state" => "VA", "slug" => "virginia-beach-city-va"],
            ["county" => "Warren", "display" => "Warren, PA", "fips" => 42123, "state" => "PA", "slug" => "warren-pa"],
            ["county" => "Washington", "display" => "Washington, PA", "fips" => 42125, "state" => "PA", "slug" => "washington-pa"],
            ["county" => "Washington", "display" => "Washington, DC", "fips" => 11001, "state" => "DC", "slug" => "washington-dc"],
            ["county" => "Warren", "display" => "Warren, NJ", "fips" => 34041, "state" => "NJ", "slug" => "warren-nj"],
            ["county" => "Warren", "display" => "Warren, VA", "fips" => 51187, "state" => "VA", "slug" => "warren-va"],
            ["county" => "Wayne", "display" => "Wayne, PA", "fips" => 42127, "state" => "PA", "slug" => "wayne-pa"],
            ["county" => "Wicomico", "display" => "Wicomico, MD", "fips" => 24045, "state" => "MD", "slug" => "wicomico-md"],
            ["county" => "Westmoreland", "display" => "Westmoreland, PA", "fips" => 42129, "state" => "PA", "slug" => "westmoreland-pa"],
            ["county" => "Winchester City", "display" => "Winchester City, VA", "fips" => 51840, "state" => "VA", "slug" => "winchester-city-va"],
            ["county" => "Waynesboro City", "display" => "Waynesboro City, VA", "fips" => 51820, "state" => "VA", "slug" => "waynesboro-city-va"],
            ["county" => "Westmoreland", "display" => "Westmoreland, VA", "fips" => 51193, "state" => "VA", "slug" => "westmoreland-va"],
            ["county" => "Wyoming", "display" => "Wyoming, PA", "fips" => 42131, "state" => "PA", "slug" => "wyoming-pa"],
            ["county" => "Wythe", "display" => "Wythe, VA", "fips" => 51197, "state" => "VA", "slug" => "wythe-va"],
            ["county" => "Worcester", "display" => "Worcester, MD", "fips" => 24047, "state" => "MD", "slug" => "worcester-md"],
            ["county" => "Wood", "display" => "Wood, WV", "fips" => 54107, "state" => "WV", "slug" => "wood-wv"],
            ["county" => "Wise", "display" => "Wise, VA", "fips" => 51195, "state" => "VA", "slug" => "wise-va"],
            ["county" => "York", "display" => "York, CT", "fips" => 9015, "state" => "CT", "slug" => "york-ct"],
            ["county" => "York", "display" => "York, PA", "fips" => 42133, "state" => "PA", "slug" => "york-pa"],
            ["county" => "York", "display" => "York, VA", "fips" => 51199, "state" => "VA", "slug" => "york-va"],
            ["county" => "York", "display" => "York, WI", "fips" => 55019, "state" => "WI", "slug" => "york-wi"],
        ];
        foreach (array_chunk($data, 500) as $chunk) {
            DB::table('county_states')->insert($chunk);
        }
    }
}