<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UpgradeFeaturesSeeder extends Seeder
{
    public function run(): void
    {
        $features = [
            [
                'feature' => 'Market Data',
                'description' => 'Analyze market data by State, County, City, or however you see fit to get key insights into how the market is moving day to day. Uncover properties recently purchased or sold by Investors.',
                'group' => 3,
                'order' => 4,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Owner Info',
                'description' => 'Find info on unlisted properties, such as owner info, names, mortgage amounts and sale dates, and previous transaction history.',
                'group' => 3,
                'order' => 8,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Gold Filters',
                'description' => 'Easily filter and sort in your subscribed county to find your perfect matches. Filter for Flips, Rentals, Wholesale deals, and other advanced methods that make finding the best deals possible with the click of a button.',
                'group' => 3,
                'order' => 1,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Revamp University',
                'description' => 'Access educational content to improve your real estate investment knowledge. Learn in depth about not only the Revamp software suite, but also access advanced trainings related to all aspects of real estate investing.',
                'group' => 3,
                'order' => 12,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Affiliate Reselling (Tier 3)',
                'description' => 'Earn though our affiliate program. Send your unique URL to your friends and when they sign up, you earn 33% on their subscription for the duration of their membership with us.',
                'group' => 3,
                'order' => 15,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Affiliate Reselling (Tier 2)',
                'description' => 'Earn though our affiliate program. Send your unique URL to your friends and when they sign up, you earn 22% on their subscription for the duration of their membership with us.',
                'group' => 3,
                'order' => 15,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Beta Features Access',
                'description' => 'Get first access to new features and updates in beta. Stay ahead with early access to the latest tools and enhancements.',
                'group' => 3,
                'order' => 4,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Focus Group',
                'description' => 'Participate in an exclusive private group for advanced investors. Collaborate and share insights with other experienced investors.',
                'group' => 3,
                'order' => 4,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Training Access',
                'description' => 'Access weekly trainings to scale your investing business. Enhance your skills and stay updated with the latest strategies.',
                'group' => 3,
                'order' => 3,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Email Tools',
                'description' => 'Use integrated email marketing tools to reach potential buyers. Say goodbye to your $500/month email marketing subscription and hello to efficency.',
                'group' => 3,
                'order' => 4,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Account Rep',
                'description' => 'Dedicated account representative to assist with your needs. Enjoy personalized support to help you navigate the platform.',
                'group' => 3,
                'order' => 1,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Weekly Calls',
                'description' => 'One-on-one weekly calls with our success manager. Receive tailored advice and guidance to optimize your investments.',
                'group' => 3,
                'order' => 2,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Automated Offers',
                'description' => 'Automatically generate and send offers based on your criteria. Simplify the offer process and save time with automation and buy more deals!',
                'group' => 3,
                'order' => 5,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Data Exporting',
                'description' => 'Export property data for further analysis or record-keeping. This feature allows for easy integration with your existing systems.',
                'group' => 3,
                'order' => 4,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Deal Alerts',
                'description' => 'Never miss a deal with alerts for properties matching your criteria. Stay informed about new investment opportunities.',
                'group' => 3,
                'order' => 2,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Rental Calculator & Reports',
                'description' => 'Access unlimited rental property reports. These reports provide comprehensive rental data to guide your investments.',
                'group' => 3,
                'order' => 9,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'List Off-Market Deals',
                'description' => 'Feature your off-market properties on our platform. Gain visibility and attract potential buyers for your exclusive listings. Access the most active investor buyers and sell your deals quicker, and for higher prices than ever before.',
                'group' => 3,
                'order' => 3,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Property Ai',
                'description' => 'Utilize AI tools for property analysis and insights. These tools enhance your investment decisions with advanced analytics. Chat with OpenAi directly from the property window and unlock intelligence beyond your imagination.',
                'group' => 3,
                'order' => 4,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Flip Calculator & Reports',
                'description' => 'Generate unlimited reports on potential flip properties. Evaluate multiple flip opportunities with detailed reports.',
                'group' => 3,
                'order' => 10,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Pending/Closed Data',
                'description' => 'View data on pending and closed MLS transactions. Understand market trends with up-to-date transaction information. No licensing required. Full access.',
                'group' => 3,
                'order' => 4,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'View Wholesale Deals',
                'description' => 'Access to exclusive wholesale deals not available in the free plan. Unlock deals and grow faster and more profitably.',
                'group' => 3,
                'order' => 3,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'MLS COMP Data',
                'description' => 'Get detailed comparable sales data from the MLS. This helps in accurate property valuation and investment analysis. No licensing required. Full access.',
                'group' => 3,
                'order' => 5,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Unlock Data Fields',
                'description' => 'Get access to premium data fields for more detailed property information. View critical information from the property thumbnail to turbocharge what deals you want to evaluate, and what you want to skip.',
                'group' => 3,
                'order' => 12,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Revamp University',
                'description' => 'Access educational content to improve your real estate investment knowledge. Learn in depth about not only the Revamp software suite, but also access advanced trainings related to all aspects of real estate investing.',
                'group' => 2,
                'order' => 12,
                'no_access' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Rental Calculator',
                'description' => 'Estimate rental income and expenses with our rental calculator. Use this feature to assess the profitability of rental properties.',
                'group' => 2,
                'order' => 11,
                'no_access' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Flip Calculator',
                'description' => 'Calculate potential flip profits and costs with our flip calculator. This tool helps you evaluate the financial feasibility of flipping properties.',
                'group' => 2,
                'order' => 10,
                'no_access' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Advanced Sorting',
                'description' => 'Sort properties using various advanced sorting options. Organize listings based on your preferred parameters.',
                'group' => 2,
                'order' => 9,
                'no_access' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Gold Filters',
                'description' => 'Use advanced filters to narrow down your property searches more effectively. This helps you find properties that meet specific investment criteria.',
                'group' => 2,
                'order' => 8,
                'no_access' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'MLS Comps',
                'description' => 'Access comparable sales data for properties to better understand market values. This helps you make informed investment decisions. Unlock the power of the MLS without licensing requirements.',
                'group' => 2,
                'order' => 5,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Auto Valuations',
                'description' => 'Leverage our database to see automated valuations. Analyze quicker, spend more time making deals and less time hunting.',
                'group' => 2,
                'order' => 6,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Deal Alerts',
                'description' => 'Receive basic filter function alerts for new deals that match your criteria. Stay updated with opportunities that fit your investment strategy.',
                'group' => 2,
                'order' => 7,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Affiliate Reselling (Tier 1)',
                'description' => 'Earn though our affiliate program. Send your unique URL to your friends and when they sign up, you earn 11% on their subscription for the duration of their membership with us.',
                'group' => 2,
                'order' => 4,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Save Properties',
                'description' => 'Save your favorite properties to easily revisit them later. This makes it convenient to keep track of potential investments.',
                'group' => 2,
                'order' => 3,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Browse MLS Deals',
                'description' => 'View a wide range of MLS property listings to find your next investment opportunity. This feature provides comprehensive access to current real estate market listings.',
                'group' => 2,
                'order' => 1,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feature' => 'Revamp Wholesale Listings',
                'description' => 'View wholesale inventory specifically from Revamp 365.',
                'group' => 2,
                'order' => 2,
                'no_access' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('upgrade_features')->insert($features);
    }
} 